apiVersion: v1
kind: Pod
metadata:
  name: hello-slsa-manual
spec:
  restartPolicy : OnFailure
  containers:
  - name: hello-slsa-manual
    image: ghcr.io/albasystems/hello-slsa:manual
    imagePullPolicy: Always