apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-signature
spec:
  validationFailureAction: Enforce
  webhookTimeoutSeconds: 30
  rules:
    - name: verify-signature
      match:
        any:
        - resources:
            kinds:
              - Pod
      verifyImages:
      - imageReferences:
        - "ghcr.io/albasystems/hello-slsa*"
        attestors:
        - entries:
          - keyless:
              subject: https://github.com/albasystems/hello-slsa/.github/workflows/build.yml@*
              issuer: "https://token.actions.githubusercontent.com"
              additionalExtensions:
                githubWorkflowRepository: albasystems/hello-slsa
              rekor:
                url: https://rekor.sigstore.dev